// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations / introspection use the DIRECT (unpooled) Neon connection.
    // The app's runtime connection (pooled DATABASE_URL) is configured in src/lib/db.ts.
    url: process.env["DIRECT_URL"],
  },
});
